-- AlterTable
ALTER TABLE "Station" ADD COLUMN     "register_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "register_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
